name: Get A Record

permissions:
  contents: write

on:
  push:
    paths:
      - 'domain.txt'
  schedule:
    - cron: '0 6 */1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # 根据你的需求指定具体版本

    - name: Install dependencies
      run: |
        pip install dnspython  # 安装dnspython库，因为你的脚本依赖它
        pip install requests

    - name: Run script to get A records
      run: |
        python domain_ip.py  
    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions Bot"
        if [ -n "$(git status --porcelain)" ]; then
          git add domain_ips.txt
          git commit -m "Automatic update"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
