name: Update IP List

permissions:
  contents: write

on:
  push:
    paths:
      - domain_ips.js
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch: # 允许手动触发

jobs:

  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set time zone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Asia/Shanghai"
        timezoneMacos: "Asia/Shanghai"
        timezoneWindows: "China Standard Time"
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests==2.32.3
        pip install beautifulsoup4==4.12.3
        pip install lxml==5.3.0
        pip install selenium==4.27.1
        pip install webdriver-manager


    # - name: Install ChromeDriver
     # run: |
       #   sudo rm -rf /usr/local/bin/chromedriver
          # 使用 wget 下载
          #wget -q -O /tmp/chromedriver-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.264/linux64/chromedriver-linux64.zip
         # cd /tmp
         # unzip chromedriver-linux64.zip
         # rm -rf chromedriver-linux64.zip
         # sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
         # sudo chmod +x /usr/local/bin/chromedriver
          #chromedriver --version

    - name: Run script
      run: python ${{ github.workspace }}/collect_ips.py

    - name: 'Install dependencies'
      run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: 'run dnscf'
      env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_DNS_NAME: ${{ secrets.CF_DNS_NAME }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python dnscf.py
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "⌚️$(date +%Y%m%d%H%M%S)" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        # github_token: ${{ secrets.GH_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}