name: Update IP List

on:
  schedule:
    - cron: '*/15 * * * *' # 每3小时运行一次
  workflow_dispatch: # 允许手动触发
  push: # 允许提交触发

jobs:

  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set time zone
      uses: szenius/set-timezone@v1.2
      with:
        timezoneLinux: "Asia/Shanghai"
        timezoneMacos: "Asia/Shanghai"
        timezoneWindows: "China Standard Time"
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install lxml
        pip install selenium


    - name: Install ChromeDriver
      run: |
          wget -q -O /tmp/chromedriver-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.84/linux64/chromedriver-linux64.zipchromedriver_linux64.zip
          cd /tmp
          unzip chromedriver-linux64.zip
          rm -rf chromedriver-linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver-linux64/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver-linux64/chromedriver
          chromedriver --version

    - name: Run script
      run: python ${{ github.workspace }}/collect_ips.py
        
    - name: Commit and push changes
      run: |
        git config --global user.email "leung0108@gmail.com"
        git config --global user.name "leung7963"
        if [ -n "$(git status --porcelain)" ]; then
          git add ip.txt
          git commit -m "Automatic update"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
